### ISSUE TITLE
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by Anaziety** [tonykipkemboi/ollama_pdf_rag#16]
My PDF is not uploading. It's giving following error:

ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

**Comment by ayus786** [comment]
I'm facing the same issue

**Comment by ToniVacaESAT** [comment]
I have the same problem with a portable installation. Everything is fine, in fact, I have another installation (which I don't dare to touch) that works perfectly. In clean installations (I've already done 10 or 12) I have already updated ComfyUI, the Reactor install.bat and the already hackneyed: "python_embeded\python.exe -m pip install --upgrade --force-reinstall insightface-0.7.3-cp311-cp311-win_amd64.whl" countless times and it doesn't fix it. I have asked ChatGPT who has suggested countless reinstallations that don't solve the problem. I hope the version that still works for me doesn't break. It's very frustrating.

**Comment by jalejandro0211** [comment]
Downgrade pip install onnx==1.16.1  

> My PDF is not uploading. It's giving following error:
> 
> ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

**Comment by juanandres-montero** [comment]
> Downgrade pip install onnx==1.16.1
> 
> > My PDF is not uploading. It's giving following error:
> > ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

I had the same issue and this worked for me! Thank you!!

**Comment by ToniVacaESAT** [comment]
> Cambiar a versión inferior pip install onnx==1.16.1
> 
> > Mi PDF no se carga. Me arroja el siguiente error:
> > ImportError: Error en la carga de DLL durante la importación onnx_cpp2py_export: Falló una rutina de inicialización de la biblioteca de vínculo dinámico (DLL).

Oh my God! Thank you so much! It worked!

**Comment by tonykipkemboi** [comment]
> Downgrade pip install onnx==1.16.1  
> 
> 
> 
> > My PDF is not uploading. It's giving following error:
> 
> > 
> 
> > ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
> 
> 
> 
> 

Thank you @jalejandro0211 for the solution. I haven't had much time to review the issues lately. I've updated the requirements file to include the correct version of onnx.
