### ISSUE TITLE
Chroma.from_documents error

### ISSUE THREAD

**Issue by ImAbhishekTomar** [tonykipkemboi/ollama_pdf_rag#8]
# Add to vector database
vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=OllamaEmbeddings(model="nomic-embed-text", show_progress=True),
    collection_name="local-rag"
)

EROR: ValueError: Error raised by inference API HTTP code: 500, {"error":"[0] server cpu not listed in available servers map[]"}

**Comment by tonykipkemboi** [comment]
Hi @ImAbhishekTomar, I realized I had not updated the modules in `requirements.txt`...so please try cloning the repo again and rerunning install.
