### ISSUE TITLE
README is misleading for setting up the streamlit app

### ISSUE THREAD

**Issue by hesreallyhim** [tonykipkemboi/ollama_pdf_rag#9]
The README.md for this (very nice) project states the following:

```
Running the Streamlit application
Clone repo: Run this in your terminal

git clone https://github.com/tonykipkemboi/ollama_pdf_rag.git

Install Dependencies: Execute to install dependencies

pip install -r requirements.txt

Launch the App: Run to start the Streamlit interface on localhost

streamlit run streamlit_app.py
```

The problem is the `requirements.txt` does not really contain all the necessary dependencies to run the app (e.g. `unstructured`). I decided I wanted to see the demo before I went though the notebook. So i installed from `requirements.txt`, but when I ran `streamlit run streamlit_app.py` there were a ton of missing dependencies. These dependencies are installed as you go through the notebook. After going through the notebook, the demo app worked great.

You might consider (a) moving the `pip install` commands out of the notebook and into the `requirements.txt` (b) modifying the README to note this issue, and not suggest that the streamlit app will work just by running `pip install -r requirements.txt`.

**Comment by tonykipkemboi** [comment]
Thanks for catching them and letting me know @hesreallyhim. I uploaded the files from my phone at the airport and haven't had time to revisit them since. I appreciate your feedback. I've update the dependecies list.
